### ISSUE TITLE
update firebase project

### ISSUE THREAD

**Issue by osvaldoM** [mozdevz/DevFest18#4]
update realtime database files and firebase rules to meeet our current needs.

**Comment by thatfiredev** [comment]
I'll be working on this. I'll add our Realtime Database JSON file to this repo.

**Comment by osvaldoM** [comment]
cool stuff @rosariopfernandes . Apparently, we'll be using firestore instead of realtime db this time.

**Comment by thatfiredev** [comment]
Just Noticed. Unfortunately, firestore doesn't have the "export data as JSON" feature that the Realtime DB has. But this project does have a script that deletes all the data on Firestore and uploads the data from [docs/default-firebase-data.json](/mozdevz/DevFest18/blob/master/docs/default-firebase-data.json).
Since that's an expensive operation for Firestore, I'll send a PR updating this file with all the new data and once it's merged, we can run that script to actually send the data to Firestore.

**Comment by osvaldoM** [comment]
naruhodo !.  Does that mean we should update `docs/default-firebase-data.json` now?
